### ISSUE TITLE
Error in log Error Creating BusinessControllerClass 'DotNetNuke.Modules.Documents.DocumentController, DotNetNuke.Modules.Documents

### ISSUE THREAD

**Issue by wbonekamp** [mitchelsellers/dnnDocuments#11]
ExceptionHash:ZzlHNgMxMIdZRsFN9hbheNEmjbA=

Message:Error Creating BusinessControllerClass 'DotNetNuke.Modules.Documents.DocumentController, DotNetNuke.Modules.Documents' of module(DNN_Documents) id=(553) in tab(120) and portal(1)

StackTrace:

at DotNetNuke.Services.Search.ModuleIndexer.ThrowLogError(ModuleInfo module, Exception ex)

InnerMessage:Value cannot be null. Parameter name: type

InnerStackTrace:

at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at DotNetNuke.Services.Search.ModuleIndexer.GetModuleList(Int32 portalId)

Source:DotNetNuke

**Comment by wbonekamp** [comment]
I think the module needs a parameterless constructor...

**Comment by mitchelsellers** [comment]
We are unable to recreate this issue.  What version of DNN are you using?  What version of .NET?  And which version of the DNN Documents Module is in use?

**Comment by wbonekamp** [comment]
DNN 9.2 (upgraded from 9.1.1)

Documents 7.0.0

.Net 4.5

Checked the document module for search index, so it's getting indexed

**Comment by mitchelsellers** [comment]
Ok, interesting, we are unable to recreate this with the same environment.  Let me continue to review this.

**Comment by wbonekamp** [comment]
DNN 9.2 upgrade from 911

Documents 7.0.0

.Net 4.5

Checked the document modules for search index

**Comment by wbonekamp** [comment]
Thanks!

Just let me know when you need more info…

We have more than 1 one modules instances on 1 page….

**Comment by mitchelsellers** [comment]
Closing this since items moved to: https://github.com/DNNCommunity/DNN.Documents
