### ISSUE TITLE
Upgrade from older version (3.1.6)

### ISSUE THREAD

**Issue by sholman** [mitchelsellers/dnnDocuments#13]
I have a rather old site that is still running v 3.1.6 of the Documents module. Is there an upgrade path to 7.0.0?

If I try to install 7.0.0 over it, I get the following

SQL Execution resulted in following Exceptions:  System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DefaultFolder'. Incorrect syntax near 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:102,State:1,Class:15 --Discrepancy fix for upgrades prior to version 06.00.00 IF (SELECT COLUMNPROPERTY( OBJECT_ID('dbo.DocumentsSettings'),'AllowUserSort','AllowsNull')) IS NULL 	ALTER TABLE dbo.DocumentsSettings 		DefaultFolder NVARCHAR(2000) NULL,		CategoriesListName NVARCHAR(50) NULL,		ADD AllowUserSort BIT NULL System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.[AddDocumentsSettings]	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS INSERT INTO dbo.[DocumentsSettings] (  ModuleId,  ShowTitleLink,  SortOrder,      DisplayColumns,  UseCategoriesList,  DefaultFolder,  CategoriesListName,  AllowUserSort ) VALUES (  @ModuleId,  @ShowTitleLink,  @SortOrder,      @DisplayColumns,  @UseCategoriesList,  @DefaultFolder,  @CategoriesListName,  @AllowUserSort ) SELECT @ModuleId System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.UpdateDocumentsSettings	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS UPDATE dbo.DocumentsSettings SET    ShowTitleLink=@ShowTitleLink,       SortOrder=@SortOrder,           DisplayColumns=@DisplayColumns,       UseCategoriesList=@UseCategoriesList,       DefaultFolder=@DefaultFolder,       CategoriesListName=@CategoriesListName,       AllowUserSort=@AllowUserSort WHERE  ModuleId = @ModuleId | SQL Execution resulted in following Exceptions:  System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DefaultFolder'. Incorrect syntax near 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:102,State:1,Class:15 --Discrepancy fix for upgrades prior to version 06.00.00 IF (SELECT COLUMNPROPERTY( OBJECT_ID('dbo.DocumentsSettings'),'AllowUserSort','AllowsNull')) IS NULL 	ALTER TABLE dbo.DocumentsSettings 		DefaultFolder NVARCHAR(2000) NULL,		CategoriesListName NVARCHAR(50) NULL,		ADD AllowUserSort BIT NULL System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.[AddDocumentsSettings]	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS INSERT INTO dbo.[DocumentsSettings] (  ModuleId,  ShowTitleLink,  SortOrder,      DisplayColumns,  UseCategoriesList,  DefaultFolder,  CategoriesListName,  AllowUserSort ) VALUES (  @ModuleId,  @ShowTitleLink,  @SortOrder,      @DisplayColumns,  @UseCategoriesList,  @DefaultFolder,  @CategoriesListName,  @AllowUserSort ) SELECT @ModuleId System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.UpdateDocumentsSettings	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS UPDATE dbo.DocumentsSettings SET    ShowTitleLink=@ShowTitleLink,       SortOrder=@SortOrder,           DisplayColumns=@DisplayColumns,       UseCategoriesList=@UseCategoriesList,       DefaultFolder=@DefaultFolder,       CategoriesListName=@CategoriesListName,       AllowUserSort=@AllowUserSort WHERE  ModuleId = @ModuleId

SQL Execution resulted in following Exceptions:  System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DefaultFolder'. Incorrect syntax near 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:102,State:1,Class:15 --Discrepancy fix for upgrades prior to version 06.00.00 IF (SELECT COLUMNPROPERTY( OBJECT_ID('dbo.DocumentsSettings'),'AllowUserSort','AllowsNull')) IS NULL 	ALTER TABLE dbo.DocumentsSettings 		DefaultFolder NVARCHAR(2000) NULL,		CategoriesListName NVARCHAR(50) NULL,		ADD AllowUserSort BIT NULL System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.[AddDocumentsSettings]	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS INSERT INTO dbo.[DocumentsSettings] (  ModuleId,  ShowTitleLink,  SortOrder,      DisplayColumns,  UseCategoriesList,  DefaultFolder,  CategoriesListName,  AllowUserSort ) VALUES (  @ModuleId,  @ShowTitleLink,  @SortOrder,      @DisplayColumns,  @UseCategoriesList,  @DefaultFolder,  @CategoriesListName,  @AllowUserSort ) SELECT @ModuleId System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DefaultFolder'. Invalid column name 'CategoriesListName'. Invalid column name 'AllowUserSort'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:16443592-7ca4-4559-89ef-0d2f178a4b32 Error Number:207,State:1,Class:16 CREATE PROCEDURE dbo.UpdateDocumentsSettings	@ModuleId          INT,	@ShowTitleLink     BIT,	@SortOrder         NVARCHAR(2000),	@DisplayColumns    NVARCHAR(2000),	@UseCategoriesList BIT,	@DefaultFolder     NVARCHAR(2000),	@CategoriesListName NVARCHAR(50),	@AllowUserSort     BIT AS UPDATE dbo.DocumentsSettings SET    ShowTitleLink=@ShowTitleLink,       SortOrder=@SortOrder,           DisplayColumns=@DisplayColumns,       UseCategoriesList=@UseCategoriesList,       DefaultFolder=@DefaultFolder,       CategoriesListName=@CategoriesListName,       AllowUserSort=@AllowUserSort WHERE  ModuleId = @ModuleId

**Comment by sholman** [comment]
I attempted to upgrade to V 6.0.0 and the upgrade went through, but now the modules show the following error


Error: Employee Documents is currently unavailable.     DotNetNuke.Services.Exceptions.ModuleLoadException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.ArgumentNullException: Value cannot be null. Parameter name: type   at System.Activator.CreateInstance(Type type, Boolean nonPublic)   at System.Activator.CreateInstance(Type type)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectProviderName, String ObjectNamespace, String ObjectAssemblyName, Boolean UseCache, Boolean fixAssemblyName)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectNamespace, String ObjectAssemblyName)   at DotNetNuke.Modules.Documents.DataProvider.CreateProvider()   at DotNetNuke.Modules.Documents.DataProvider..cctor()   --- End of inner exception stack trace ---   at DotNetNuke.Modules.Documents.DocumentController.GetDocumentsSettings(Int32 ModuleId)   at DotNetNuke.Modules.Documents.Document.LoadSettings()   at DotNetNuke.Modules.Documents.Document.Page_Load(Object sender, EventArgs e)   --- End of inner exception stack trace --- | Error: Employee Documents is currently unavailable.     DotNetNuke.Services.Exceptions.ModuleLoadException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.ArgumentNullException: Value cannot be null. Parameter name: type   at System.Activator.CreateInstance(Type type, Boolean nonPublic)   at System.Activator.CreateInstance(Type type)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectProviderName, String ObjectNamespace, String ObjectAssemblyName, Boolean UseCache, Boolean fixAssemblyName)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectNamespace, String ObjectAssemblyName)   at DotNetNuke.Modules.Documents.DataProvider.CreateProvider()   at DotNetNuke.Modules.Documents.DataProvider..cctor()   --- End of inner exception stack trace ---   at DotNetNuke.Modules.Documents.DocumentController.GetDocumentsSettings(Int32 ModuleId)   at DotNetNuke.Modules.Documents.Document.LoadSettings()   at DotNetNuke.Modules.Documents.Document.Page_Load(Object sender, EventArgs e)   --- End of inner exception stack trace ---
-- | --
Error: Employee Documents is currently unavailable.     DotNetNuke.Services.Exceptions.ModuleLoadException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception. ---> System.ArgumentNullException: Value cannot be null. Parameter name: type   at System.Activator.CreateInstance(Type type, Boolean nonPublic)   at System.Activator.CreateInstance(Type type)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectProviderName, String ObjectNamespace, String ObjectAssemblyName, Boolean UseCache, Boolean fixAssemblyName)   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectNamespace, String ObjectAssemblyName)   at DotNetNuke.Modules.Documents.DataProvider.CreateProvider()   at DotNetNuke.Modules.Documents.DataProvider..cctor()   --- End of inner exception stack trace ---   at DotNetNuke.Modules.Documents.DocumentController.GetDocumentsSettings(Int32 ModuleId)   at DotNetNuke.Modules.Documents.Document.LoadSettings()   at DotNetNuke.Modules.Documents.Document.Page_Load(Object sender, EventArgs e)   --- End of inner exception stack trace ---

**Comment by sholman** [comment]
This is on DNN 7.4.2

**Comment by mitchelsellers** [comment]
There were legacy packaging issues that were not able to be resolved.  The upgrade to 6.0.0 as you did is a good first step.

You will need to look in your /bin folder and delete a file that is DotnetNuke.Modules.Documents.SqlDataProvider.dll (or similar) if it exists.

**Comment by sholman** [comment]
That worked, thanks for the fast reply Mitchel

**Comment by mitchelsellers** [comment]
Glad to help!
