### ISSUE TITLE
Compatbility with DNN 9.2.0

### ISSUE THREAD

**Issue by benjironelson** [mitchelsellers/dnnDocuments#9]
Hi Mitchell,

I just got word that this module does not work with DNN 9.2.0. I am not sure if you are still developing it, but I figured I would pass this info along.

Message:Could not load type 'DotNetNuke.Services.FileSystem.FileController' from assembly 'DotNetNuke, Version=9.2.0.366, Culture=neutral, PublicKeyToken=null'.

StackTrace:

InnerMessage:Could not load type 'DotNetNuke.Services.FileSystem.FileController' from assembly 'DotNetNuke, Version=9.2.0.366, Culture=neutral, PublicKeyToken=null'.

InnerStackTrace:

at DotNetNuke.Modules.Documents.Document.LoadData() at DotNetNuke.Modules.Documents.Document.Page_Load(Object sender, EventArgs e)

**Comment by david-poindexter** [comment]
DNN 9.2.0 came with the removal of over 500 deprecated APIs.  This is likely the cause.

**Comment by mitchelsellers** [comment]
Yes, the deprecated API's have caused an issue.

I'm working to try and get a release for this in the next few days.  Its been a bit crazy around here

**Comment by mitchelsellers** [comment]
A partial commit with fixes are there.  Working to get the rest done

**Comment by valadas** [comment]
I submitted another pull request that completes it for dnn 9.2 compatibility
